BoxingList/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BoxingList.Models
{
    public class ApplicationDbContext : DbContext 
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {

        }

        public DbSet<Boxer> Boxers { get; set; }
    }
}

BoxingList/Models/Boxer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BoxingList.Models
{
    public class Boxer
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string Division { get; set; }
        public string Record { get; set; }
    }
}

BoxingList/Models/ErrorViewModel.cs
using System;

namespace BoxingList.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BoxingList/Controllers/BoxersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BoxingList.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BoxingList.Controllers
{
    public class BoxersController : Controller
    {

        private readonly ApplicationDbContext _db;

        public BoxersController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View(_db.Boxers.ToList());
        }

        //GET Boxer/Create
        public IActionResult Create()
        {
            //Load container for name, division and record
            return View();
        }

        //POST CREATE BOXER
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Boxer boxer)
        {
            if (ModelState.IsValid)
            {
                _db.Add(boxer);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(boxer);
        }

        //GET EDIT BOXER INFO
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) //Required Property reverification as specified in Model
            {
                return NotFound();
            }

            var boxer = await _db.Boxers.SingleOrDefaultAsync(m => m.Id == id);

            if (boxer == null)  //Required Property reverification as specified in Model
            {
                return NotFound();
            }

            return View(boxer);
        }

        //POST EDIT BOXER INFO
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Boxer boxer)
        {
            if (ModelState.IsValid)
            {
                //_db.Update(boxer);

                var BoxerfromDb = await _db.Boxers.FirstOrDefaultAsync(b => b.Id == boxer.Id);
                BoxerfromDb.Name = boxer.Name;
                BoxerfromDb.Division = boxer.Division;
                BoxerfromDb.Record = boxer.Record;

                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(boxer);
        }

        //GET DELETE BOXER 
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) //Required Property reverification as specified in Model
            {
                return NotFound();
            }

            var boxer = await _db.Boxers.SingleOrDefaultAsync(m => m.Id == id);

            if (boxer == null)  //Required Property reverification as specified in Model
            {
                return NotFound();
            }

            return View(boxer);
        }

        //POST DELETE BOXER
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveBoxer(int? id)
        {
            var boxer = await _db.Boxers.SingleOrDefaultAsync(m => m.Id == id);
            _db.Boxers.Remove(boxer);

            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }

        //GET DETAILS BOXER 
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) //Required Property reverification as specified in Model
            {
                return NotFound();
            }

            var boxer = await _db.Boxers.SingleOrDefaultAsync(m => m.Id == id);

            if (boxer == null)  //Required Property reverification as specified in Model
            {
                return NotFound();
            }

            return View(boxer);
        }
    }
}

BoxingList/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BoxingList.Models;

namespace BoxingList.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BoxingList/Views/Boxers/Create.cshtml
@model BoxingList.Models.Boxer
@{
    ViewData["Title"] = "Create";
}

<br />
<h2>Add New Boxer</h2>
<hr />

<form asp-action ="Create">
    <div class=" container">
        <div class="form-group">
            <div class=" row">
                <div class="col-sm-1">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Name" class="form-control" />
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class=" row">
                <div class="col-sm-1">
                    <label asp-for="Division"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Division" class="form-control" />
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class=" row">
                <div class="col-sm-1">
                    <label asp-for="Record"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Record" class="form-control" />
                </div>
            </div>
        </div>
        <br />
        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-sm btn-primary" />
            <a asp-action="Index" class="btn btn-sm btn-success">Back to Boxing List</a>
        </div>
    </div>

</form>

BoxingList/Views/Boxers/Delete.cshtml
@model BoxingList.Models.Boxer
@{
    ViewData["Title"] = "Delete";
}

<br />
<h2>Delete Boxer</h2>
<hr />

<form asp-action="Delete">
    <div class=" container">
        <input asp-for="Id" hidden />
        <div class="form-group">
            <div class=" row">
                <div class="col-sm-1">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Name" disabled class="form-control" />
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class=" row">
                <div class="col-sm-1">
                    <label asp-for="Division"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Division" disabled class="form-control" />
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class=" row">
                <div class="col-sm-1">
                    <label asp-for="Record"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Record" disabled class="form-control" />
                </div>
            </div>
        </div>
        <br />
        <div class="form-group">
            <input type="submit" value="Delete" class="btn btn-sm btn-danger" />
            <a asp-action="Index" class="btn btn-sm btn-success">Back to Boxing List</a>
        </div>
    </div>

</form>

BoxingList/Views/Boxers/Details.cshtml
@model BoxingList.Models.Boxer
@{
    ViewData["Title"] = "Details";
}

<br />
<h2>Details of Boxer</h2>
<hr />

<form asp-action="Details">
    <div class=" container">
        <input asp-for="Id" hidden />
        <div class="form-group">
            <div class=" row">
                <div class="col-sm-1">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Name" disabled class="form-control" />
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class=" row">
                <div class="col-sm-1">
                    <label asp-for="Division"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Division" disabled class="form-control" />
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class=" row">
                <div class="col-sm-1">
                    <label asp-for="Record"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Record" disabled class="form-control" />
                </div>
            </div>
        </div>
        <br />
        <div class="form-group">
            <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-sm btn-primary">Edit</a>
            <a asp-action="Index" class="btn btn-sm btn-success">Back to Boxing List</a>
        </div>
    </div>

</form>

BoxingList/Views/Boxers/Edit.cshtml
@model BoxingList.Models.Boxer
@{
    ViewData["Title"] = "Edit";
}

<br />
<h2>Edit Boxer</h2>
<hr />

<form asp-action="Edit">
    <div class=" container">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <div class=" row">
                <div class="col-sm-1">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Name" class="form-control" />
                </div>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class=" row">
                <div class="col-sm-1">
                    <label asp-for="Division"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Division" class="form-control" />
                </div>
                <span asp-validation-for="Division" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class=" row">
                <div class="col-sm-1">
                    <label asp-for="Record"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Record" class="form-control" />
                </div>
                <span asp-validation-for="Record" class="text-danger"></span>
            </div>
        </div>
        <br />
        <div class="form-group">
            <input type="submit" value="Update" class="btn btn-sm btn-primary" />
            <a asp-action="Index" class="btn btn-sm btn-success">Back to Boxing List</a>
        </div>
    </div>

</form>

BoxingList/Views/Boxers/Index.cshtml
@model IEnumerable<BoxingList.Models.Boxer>
@{
    ViewData["Title"] = "Index";
}

<br />
<h3>Boxer List</h3>

<hr />
<p>
    <a asp-action="Create" class="btn btn-sm btn-primary">Create New</a> 
</p>

@if (Model.Count() > 0)
{
    //Display all boxers
    <div class="border">
        <table class="table">
            <tr>
                <th>@Html.DisplayNameFor(m => m.Name)</th>
                <th>@Html.DisplayNameFor(m => m.Division)</th>
                <th>@Html.DisplayNameFor(m => m.Record)</th>
                <th></th>
            </tr>
            @foreach(var item in Model)
            {
        <tr>
            <td>
                @Html.DisplayFor(m => item.Name)
            </td>
            <td>
                @Html.DisplayFor(m => item.Division)
            </td>
            <td>
                @Html.DisplayFor(m => item.Record)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-success">Edit</a>
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-primary">Details</a>
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger">Delete</a>
            </td>
        </tr>
            }
        </table>
    </div>
}
else
{
    <div>No Boxers Exists... Please Add a new boxer.</div>
}

BoxingList/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Boxing List Application</h1> 
    <hr />

    <p> This is an application that allows you to create a boxer, edit its information and also delete it from the list.</p>
    <br />
    <p> Start exploring by choosing the "Boxer List" option</p>
</div>

BoxingList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Boxing List</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background-color:lightgray">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BoxingList</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Boxers" asp-action="Index">Boxer List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - BoxingList - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>